### ISSUE TITLE
Express gateway crashing due to invalid code in rewrite plugin dependency

### ISSUE THREAD

**Issue by imthinhvu** [ExpressGateway/express-gateway-plugin-rewrite#3]
After installing the rewrite plugin via the CLI and attempting to start the gateway, I receive an error from the path-to-regexp dependency of the rewrite plugin:

```
npm start

> trip-planner-api@1.0.0 start /Users/thivu/Development/trip-planner-api
> node server.js

/Users/thivu/Development/trip-planner-api/node_modules/express-gateway-plugin-rewrite/node_modules/path-to-regexp/index.js:99
  if (path || index < str.length) {
                          ^

TypeError: Cannot read property 'length' of undefined
    at parse (/Users/thivu/Development/trip-planner-api/node_modules/express-gateway-plugin-rewrite/node_modules/path-to-regexp/index.js:99:27)
    at Function.compile (/Users/thivu/Development/trip-planner-api/node_modules/express-gateway-plugin-rewrite/node_modules/path-to-regexp/index.js:114:27)
    at policy (/Users/thivu/Development/trip-planner-api/node_modules/express-gateway-plugin-rewrite/manifest.js:13:42)
    at pipelinePoliciesConfig.forEach.policyConfig (/Users/thivu/Development/trip-planner-api/node_modules/express-gateway/lib/gateway/pipelines.js:166:32)
    at Array.forEach (<anonymous>)
    at configurePipeline (/Users/thivu/Development/trip-planner-api/node_modules/express-gateway/lib/gateway/pipelines.js:142:26)
    at Object.module.exports.bootstrap (/Users/thivu/Development/trip-planner-api/node_modules/express-gateway/lib/gateway/pipelines.js:49:18)
    at bootstrap (/Users/thivu/Development/trip-planner-api/node_modules/express-gateway/lib/gateway/index.js:89:26)
    at module.exports (/Users/thivu/Development/trip-planner-api/node_modules/express-gateway/lib/gateway/index.js:19:37)
    at Main.run (/Users/thivu/Development/trip-planner-api/node_modules/express-gateway/lib/index.js:24:27)
    at Object.<anonymous> (/Users/thivu/Development/trip-planner-api/server.js:6:4)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! trip-planner-api@1.0.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the trip-planner-api@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/thivu/.npm/_logs/2017-10-17T23_43_10_162Z-debug.log
```

**Comment by DrMegavolt** [comment]
can you provide config example? 
from what I see in line 13 in stack trace
`      const compiledExp = pathToRegExp.compile(actionParams.rewrite);`
it looks like no `rewrite` property

**Comment by XVincentX** [comment]
Note:
Once the schema support in the gateway will be published, I'll definitely make a PR and add a schema for the parameters so this should not happen anymore.

**Comment by XVincentX** [comment]
@imthinhvu Did you solve your issue?

**Comment by imthinhvu** [comment]
@XVincentX I did not. I ended up giving up on express-gateway for now as I didn't want to deal with not knowing the file configuration specifics, and I don't have the time to dig into issues like this to figure it out.

**Comment by XVincentX** [comment]
That's sad to hear — I'd love to know more about that. Did you find the documentation hard to navigate? Or is the configuration file just hard to reason about?

I'm going to close this one for now — feel free to reopen if you'd like to dig into this again!

**Comment by imthinhvu** [comment]
@XVincentX For the most part, the documentation is pretty easy to navigate--I did not have a bad experience going through the initial "Getting Started" steps. I did find some difficulty around the configuration with plugins, however, and think there can be some work done there. I have no doubt that your suggested fix would have fixed my problem, but I also would've expected a simple fix like that to error out properly to the user. Express-Gateway seems like a great product, but as of right now, in my opinion, it's just not mature enough to try to use in an enterprise setting. I will definitely try revisiting it again in the near future. Thanks for all of the hard work!

**Comment by XVincentX** [comment]
I totally get your concerns — and one more time thank you for taking the time for filing the issue.

About this one in particular, the upcoming gateway releases will have a schema validation feature that should hopefully totally prevent these problems in the future. We try to improve as we go, and offer the best support we can.

> It's just not mature enough to try to use in an enterprise setting

That's a fair point. What's sure is that we do not really have super enterprise on our "curriculum" yet — although Joyent is actively using us and giving great feedbacks.

I hope you're going to come back one of those days — and see you happy!
